kind: pipeline
name: default

steps:
- name: branch-build
  image: golang
  commands:
    - sleep 15
    - go test -short
    - echo "This is branch-build!"
  when:
    event:
      - push
     
- name: pr-build
  image: golang
  commands:
    - sleep 15
    - go test -v
    - echo "This is pr-build!"
  when:
    event:
      - pull_request
