kind: pipeline
name: default

steps:
- name: test
  image: redis
  commands:
  - sleep 60
  - redis-cli -h redis ping
  - redis-cli -h redis set FOO bar
  - redis-cli -h redis get FOO
  - echo "Hello Redis!"

services:
- name: redis
  image: redis
  ports:
  - 6379
