kind: pipeline
name: default

env:
 - GOPATH=/var/cache/drone

steps:
- name: test
  image: golang
  commands:
  - sleep 15
  - go test -v 
  - echo "Hello Drone!"
  - uptime
  - df -h
  - free -h
  - sleep 3
