kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
    - sleep 15
    - go test -short
    - echo "This is branch-build!"
  when:
    event:
      - push
     
- name: test-pr
  image: golang
  commands:
    - sleep 15
    - go test -v
    - echo "This is pr-build!"
  when:
    event:
      - pull_request
